// src/frontend/src/app/components/playlist-box/playlist-box.component.ts
import {Component, Input} from '@angular/core';
import {AsyncPipe, CommonModule, NgIf} from "@angular/common";
import {TrackListComponent} from "../track-list/track-list.component";
import {PlaylistService, PlaylistStatusEnum, PlaylistUi} from "../../services/playlist.service";
import {Observable, map} from "rxjs";
import {Playlist} from "../../models/playlist";

const STATUS2CLASS = {
  [PlaylistStatusEnum.Completed]: 'is-success',
  [PlaylistStatusEnum.InProgress]: 'is-info',
  [PlaylistStatusEnum.Warning]: 'is-warning',
  [PlaylistStatusEnum.Error]: 'is-danger',
  [PlaylistStatusEnum.Subscribed]: 'is-primary',
}

@Component({
    selector: 'app-playlist-box',
    imports: [
        CommonModule,
        AsyncPipe,
        NgIf,
        TrackListComponent
    ],
    templateUrl: './playlist-box.component.html',
    styleUrl: './playlist-box.component.scss',
  standalone: true
})
export class PlaylistBoxComponent {

  @Input() set playlist(val: Playlist & PlaylistUi) {
    this._playlist = val;
    this.trackCount$ = this.service.getTrackCount(val.id);
    this.trackCompletedCount$ = this.service.getCompletedTrackCount(val.id);
    this.statusClass$ = this.service.getStatus$(val.id).pipe(
      map(status => STATUS2CLASS[status])
    );
  }
  get playlist(): Playlist & PlaylistUi {
    return this._playlist;
  }
  _playlist!: Playlist & PlaylistUi;
  trackCount$!: Observable<number>;
  trackCompletedCount$!: Observable<number>;
  statusClass$!: Observable<string>;

  constructor(private readonly service: PlaylistService) { }

  getDisplayName(): string {
    if (!this.playlist.name) return '';
    
    // For tracks and albums, format as "Artist - Title"
    if (this.playlist.type === 'track' || this.playlist.type === 'album') {
      return this.playlist.name;
    }
    
    // For playlists, show name as-is
    return this.playlist.name;
  }

  toggleCollapse(playlistId: number): void {
    this.service.toggleCollapsed(playlistId);
  }

  delete(id: number): void {
    this.service.delete(id);
  }

  retryFailed(id: number): void {
    this.service.retryFailed(id);
  }

  toggleActive(id: number, currentActive: boolean): void {
    this.service.setActive(id, !currentActive)
  }
}

<article class="border-2 dark:border-spotify-gray-medium rounded-xl mb-4 overflow-hidden bg-gray-50 dark:bg-spotify-gray-medium hover:border-spotify-green transition-all" [ngClass]="statusClass$ | async">
  <p class="bg-gradient-to-r from-gray-100 to-gray-50 dark:from-spotify-gray-dark dark:to-spotify-gray-medium px-5 py-4 flex justify-between items-center border-b-2 dark:border-spotify-gray-dark">
        <span class="flex items-center gap-3">
          <i class="cursor-pointer fa-solid text-spotify-green text-lg hover:scale-110 transition-transform"
             [ngClass]="playlist.collapsed ? 'fa-caret-down' : 'fa-caret-right'"
             (click)="toggleCollapse(playlist.id)"
          ></i>
          <span *ngIf="playlist.error; else noErrorTemplate" class="text-base font-semibold text-red-500 dark:text-red-400">{{playlist.error}}</span>
          <ng-template #noErrorTemplate>
            <span class="text-base font-bold dark:text-white">{{getDisplayName()}}</span>
          </ng-template>
          <a [href]="playlist.spotifyUrl"
             target="_blank"
             class="text-spotify-green hover:text-spotify-green-light hover:scale-110 transition-all" title="Open in Spotify">
            <i class="fa-brands fa-spotify text-lg"></i>
          </a>
        </span>
    <span class="flex items-center gap-3 text-spotify-gray-light dark:text-spotify-gray-light">
      <i class="fa-solid cursor-pointer hover:text-spotify-green hover:scale-110 transition-all"
         [ngClass]="playlist.active ? 'fa-toggle-on text-spotify-green' : 'fa-toggle-off'"
         [title]="playlist.active ? '[ON]: Unsubscribe from playlist changes?' : '[OFF]: Subscribe to playlist changes?'"
         (click)="toggleActive(playlist.id, playlist.active)"
      ></i>
      <i class="fa-solid fa-repeat cursor-pointer hover:text-spotify-green hover:scale-110 transition-all" title="Retry download failed tracks" (click)="retryFailed(playlist.id)"></i>
      <i class="fa-solid fa-xmark cursor-pointer hover:text-red-500 hover:scale-110 transition-all" title="Remove playlist from list" (click)="delete(playlist.id)"></i>
      <span *ngIf="!playlist.error" class="text-sm font-bold bg-spotify-gray-dark dark:bg-black px-3 py-1 rounded-full">{{trackCompletedCount$ | async}}/{{trackCount$ | async}}</span>
    </span>
  </p>
  <ng-container *ngIf="playlist.collapsed">
    <app-track-list [playlistId]="playlist.id"></app-track-list>
  </ng-container>
</article>

// src/frontend/src/components/PlaylistBox.tsx
import { usePlaylists } from "@/hooks/usePlaylists";
import { useTracks } from "@/hooks/useTracks";
import { TrackStatus } from "@/types/track";
import { useUIStore } from "@/store/useUIStore";
import type { Playlist } from "@/types/playlist";
import clsx from "clsx";
import { TrackList } from "./TrackList";

interface Props {
  playlist: Playlist;
}

export const PlaylistBox = ({ playlist }: Props) => {
  const { updatePlaylist, deletePlaylist } = usePlaylists();
  const { tracks, retryTrack } = useTracks(playlist.id);
  const { collapsedPlaylists, togglePlaylistCollapse } = useUIStore();

  const isCollapsed = collapsedPlaylists.has(playlist.id);

  const completedCount = tracks.filter(
    (t) => t.status === TrackStatus.Completed,
  ).length;
  const totalCount = tracks.length;

  const handleToggleCollapse = () => {
    togglePlaylistCollapse(playlist.id);
  };

  const handleToggleActive = () => {
    updatePlaylist.mutate({
      id: playlist.id,
      data: { active: !playlist.active },
    });
  };

  const handleDelete = () => {
    if (!Number.isFinite(playlist.id)) {
      console.warn("Attempted delete playlist with invalid id", playlist.id);
      return;
    }
    deletePlaylist.mutate(playlist.id);
  };

  const handleRetryFailed = () => {
    const failedTracks = tracks.filter((t) => t.status === TrackStatus.Error);
    failedTracks.forEach((track) => retryTrack.mutate(track.id));
  };

  const getStatusClass = () => {
    if (playlist.error) return "border-red-500";
    if (playlist.active) return "border-spotify-green";
    if (completedCount === totalCount && totalCount > 0)
      return "border-green-500";
    return "";
  };

  return (
    <article
      className={clsx(
        "border-2 dark:border-spotify-gray-medium rounded-xl mb-4 overflow-hidden bg-gray-50 dark:bg-spotify-gray-medium hover:border-spotify-green transition-all",
        getStatusClass(),
      )}
    >
      <div className="bg-gradient-to-r from-gray-100 to-gray-50 dark:from-spotify-gray-dark dark:to-spotify-gray-medium px-5 py-4 flex justify-between items-center border-b-2 dark:border-spotify-gray-dark">
        <span className="flex items-center gap-3">
          <i
            className={clsx(
              "cursor-pointer fa-solid text-spotify-green text-lg hover:scale-110 transition-transform",
              isCollapsed ? "fa-caret-right" : "fa-caret-down",
            )}
            onClick={handleToggleCollapse}
          />
          {playlist.error ? (
            <span className="text-base font-semibold text-red-500 dark:text-red-400">
              {playlist.error}
            </span>
          ) : (
            <span className="text-base font-bold dark:text-white">
              {playlist.name || "Unnamed Playlist"}
            </span>
          )}
          <a
            href={playlist.spotifyUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-spotify-green hover:text-spotify-green-light hover:scale-110 transition-all"
            title="Open in Spotify"
          >
            <i className="fa-brands fa-spotify text-lg" />
          </a>
        </span>

        <span className="flex items-center gap-3 text-spotify-gray-light dark:text-spotify-gray-light">
          <i
            className={clsx(
              "fa-solid cursor-pointer hover:text-spotify-green hover:scale-110 transition-all",
              playlist.active
                ? "fa-toggle-on text-spotify-green"
                : "fa-toggle-off",
            )}
            title={
              playlist.active
                ? "[ON]: Unsubscribe from playlist changes?"
                : "[OFF]: Subscribe to playlist changes?"
            }
            onClick={handleToggleActive}
          />
          <i
            className="fa-solid fa-repeat cursor-pointer hover:text-spotify-green hover:scale-110 transition-all"
            title="Retry download failed tracks"
            onClick={handleRetryFailed}
          />
          <i
            className="fa-solid fa-xmark cursor-pointer hover:text-red-500 hover:scale-110 transition-all"
            title="Remove playlist from list"
            onClick={() => playlist.id != null && handleDelete()}
          />
          {!playlist.error && (
            <span className="text-sm font-bold bg-spotify-gray-dark dark:bg-black px-3 py-1 rounded-full">
              {completedCount}/{totalCount}
            </span>
          )}
        </span>
      </div>

      {isCollapsed && <TrackList playlistId={playlist.id} />}
    </article>
  );
};
