// src/frontend/src/components/TrackList.tsx
import { useTracks } from "@/hooks/useTracks";
import { TrackStatus } from "@/types/track";
import clsx from "clsx";

interface Props {
  playlistId: number;
}

const STATUS_CONFIG: Record<number, { label: string; className: string }> = {
  [TrackStatus.New]: {
    label: "NEW",
    className: "bg-blue-500/20 text-blue-400 border-blue-500/30",
  },
  [TrackStatus.Searching]: {
    label: "SEARCHING",
    className: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
  },
  [TrackStatus.Queued]: {
    label: "QUEUED",
    className: "bg-orange-500/20 text-orange-400 border-orange-500/30",
  },
  [TrackStatus.Downloading]: {
    label: "DOWNLOADING",
    className: "bg-purple-500/20 text-purple-400 border-purple-500/30",
  },
  [TrackStatus.Completed]: {
    label: "COMPLETED",
    className: "bg-green-500/20 text-green-400 border-green-500/30",
  },
  [TrackStatus.Error]: {
    label: "ERROR",
    className: "bg-red-500/20 text-red-400 border-red-500/30",
  },
};

export const TrackList = ({ playlistId }: Props) => {
  const { tracks, retryTrack, deleteTrack } = useTracks(playlistId);

  const handleRetry = (trackId: number) => {
    if (!Number.isFinite(trackId)) {
      console.warn("Attempted retry with invalid track id", trackId);
      return;
    }
    retryTrack.mutate(trackId);
  };

  const handleDelete = (trackId: number) => {
    if (!Number.isFinite(trackId)) {
      console.warn("Attempted delete with invalid track id", trackId);
      return;
    }
    deleteTrack.mutate(trackId);
  };

  if (tracks.length === 0) {
    return (
      <div className="px-5 py-8 text-center text-spotify-gray-light dark:text-spotify-gray-light">
        <i className="fa-solid fa-music text-3xl mb-2" />
        <p>No tracks yet</p>
      </div>
    );
  }

  return (
    <div>
      {tracks.map((track) => {
        const artists = track.artists ?? [];

        return (
          <div
            key={track.id}
            className="flex justify-between items-center px-5 py-3 border-b dark:border-spotify-gray-dark hover:bg-gray-100 dark:hover:bg-spotify-gray-dark transition-all group"
          >
            <div className="flex items-center gap-3 dark:text-white flex-wrap">
              <span className="font-medium flex items-center gap-2 flex-wrap text-sm sm:text-base">
                <span className="text-spotify-gray-light flex items-center gap-1 flex-wrap">
                  {artists.length
                    ? artists.map((artist, index) => (
                        <span key={`${artist.name}-${index}`} className="flex items-center gap-1">
                          {artist.url ? (
                            <a
                              href={artist.url}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="hover:text-spotify-green hover:underline decoration-spotify-green decoration-2 underline-offset-4 transition-colors"
                            >
                              {artist.name}
                            </a>
                          ) : (
                            <span>{artist.name}</span>
                          )}
                          {index < artists.length - 1 && (
                            <span className="text-spotify-gray-light">,</span>
                          )}
                        </span>
                      ))
                    : track.artist}
                </span>
                <span className="text-spotify-gray-light">•</span>
                {track.trackUrl || track.spotifyUrl ? (
                  <a
                    href={track.trackUrl || track.spotifyUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-black dark:text-white hover:text-spotify-green hover:underline decoration-spotify-green decoration-2 underline-offset-4 transition-colors"
                  >
                    {track.name}
                  </a>
                ) : (
                  <span className="text-black dark:text-white">{track.name}</span>
                )}
              </span>

              {track.youtubeUrl && (
                <a
                  href={track.youtubeUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-red-500 hover:text-red-600 hover:scale-110 transition-all"
                  title="View on YouTube"
                >
                  <i className="fa-brands fa-youtube" />
                </a>
              )}

              {track.status === TrackStatus.Completed && (
                <a
                  href={`/api/track/download/${track.id}`}
                  className="text-blue-500 hover:text-blue-600 hover:scale-110 transition-all"
                  title="Download file"
                  download
                >
                  <i className="fa-solid fa-download" />
                </a>
              )}
            </div>

            <div className="flex items-center gap-3">
              {track.status === TrackStatus.Error && (
                <i
                  className="fa-solid fa-repeat cursor-pointer hover:text-spotify-green hover:scale-110 transition-all text-spotify-gray-light"
                  title="Retry download"
                  onClick={() => track.id != null && handleRetry(track.id)}
                />
              )}
              <i
                className="fa-solid fa-xmark cursor-pointer hover:text-red-500 hover:scale-110 transition-all text-spotify-gray-light opacity-0 group-hover:opacity-100"
                title="Remove track"
                onClick={() => track.id != null && handleDelete(track.id)}
              />
              <span
                className={clsx(
                  "inline-block px-3 py-1 text-xs font-bold rounded-full border",
                  // defensive: fallback to Error class if unknown
                  STATUS_CONFIG[track.status]?.className ||
                    STATUS_CONFIG[TrackStatus.Error].className,
                )}
              >
                {STATUS_CONFIG[track.status]?.label ||
                  STATUS_CONFIG[TrackStatus.Error].label}
              </span>
            </div>
          </div>
        );
      })}
    </div>
  );
};

// src/frontend/src/app/components/track-list/track-list.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule, NgFor, NgSwitch, NgSwitchCase } from '@angular/common';
import { TrackService } from '../../services/track.service';
import { Observable } from 'rxjs';
import { Track, TrackStatusEnum } from '../../models/track';

@Component({
  selector: 'app-track-list',
  imports: [CommonModule, NgFor, NgSwitch, NgSwitchCase],
  templateUrl: './track-list.component.html',
  styleUrl: './track-list.component.scss',
  standalone: true,
})
export class TrackListComponent {
  @Input() set playlistId(value: number) {
    this.tracks$ = this.service.getAllByPlaylist(value);
  }
  tracks$!: Observable<Track[]>;
  trackStatuses = TrackStatusEnum;

  constructor(private readonly service: TrackService) {}

  delete(id: number): void {
    this.service.delete(id);
  }

  retry(id: number): void {
    this.service.retry(id);
  }
}

<a
  class="flex justify-between items-center px-5 py-3 border-b dark:border-spotify-gray-dark hover:bg-gray-100 dark:hover:bg-spotify-gray-dark transition-all group"
  *ngFor="let track of tracks$ | async"
>
  <div class="flex items-center gap-3 dark:text-white">
    <span class="font-medium">
      <ng-container
        *ngIf="track.artists && track.artists.length > 0; else fallbackArtist"
      >
        <ng-container *ngFor="let artist of track.artists; let isLast = last">
          <a
            [href]="artist.url"
            target="_blank"
            rel="noopener noreferrer"
            class="text-spotify-gray-light hover:text-spotify-green hover:underline transition-all"
          >
            {{ artist.name }}
          </a>
          <span *ngIf="!isLast" class="text-spotify-gray-light">, </span>
        </ng-container>
      </ng-container>
      <ng-template #fallbackArtist>
        <span class="text-spotify-gray-light mr-1">{{ track.artist }}</span>
      </ng-template>
      <span class="mx-1 text-spotify-gray-light">•</span>
      <a
        *ngIf="track.trackUrl"
        [href]="track.trackUrl"
        target="_blank"
        rel="noopener noreferrer"
        class="text-black dark:text-white hover:text-spotify-green hover:underline transition-all"
      >
        {{ track.name }}
      </a>
      <span *ngIf="!track.trackUrl" class="text-black dark:text-white">{{
        track.name
      }}</span>
    </span>
    <a
      *ngIf="track.spotifyUrl"
      [href]="track.spotifyUrl"
      target="_blank"
      class="text-spotify-green hover:text-spotify-green-light hover:scale-110 transition-all"
      title="Preview audio"
    >
      <i class="fa-solid fa-headphones"></i>
    </a>
    <span
      *ngIf="!track.spotifyUrl"
      class="text-gray-400 dark:text-gray-600 opacity-30 cursor-not-allowed"
      title="Preview not available"
    >
      <i class="fa-solid fa-headphones"></i>
    </span>
    <a
      [href]="track.youtubeUrl"
      target="_blank"
      class="text-red-500 hover:text-red-600 hover:scale-110 transition-all"
      title="View on YouTube"
    >
      <i class="fa-brands fa-youtube"></i>
    </a>
    <a
      *ngIf="track.status === trackStatuses.Completed"
      href="api/track/download/{{ track.id }}"
      class="text-blue-500 hover:text-blue-600 hover:scale-110 transition-all"
      title="Download file"
      download
    >
      <i class="fa-solid fa-download"></i>
    </a>
  </div>
  <div class="flex items-center gap-3">
    <i
      *ngIf="track.status === trackStatuses.Error"
      class="fa-solid fa-repeat cursor-pointer hover:text-spotify-green hover:scale-110 transition-all text-spotify-gray-light"
      title="Retry download"
      (click)="retry(track.id)"
    ></i>
    <i
      class="fa-solid fa-xmark cursor-pointer hover:text-red-500 hover:scale-110 transition-all text-spotify-gray-light opacity-0 group-hover:opacity-100"
      title="Remove track"
      (click)="delete(track.id)"
    ></i>
    <ng-container [ngSwitch]="track.status">
      <span
        *ngSwitchCase="trackStatuses.New"
        class="inline-block px-3 py-1 text-xs font-bold rounded-full bg-blue-500/20 text-blue-400 border border-blue-500/30"
        >NEW</span
      >
      <span
        *ngSwitchCase="trackStatuses.Searching"
        class="inline-block px-3 py-1 text-xs font-bold rounded-full bg-yellow-500/20 text-yellow-400 border border-yellow-500/30"
        >SEARCHING</span
      >
      <span
        *ngSwitchCase="trackStatuses.Queued"
        class="inline-block px-3 py-1 text-xs font-bold rounded-full bg-orange-500/20 text-orange-400 border border-orange-500/30"
        >QUEUED</span
      >
      <span
        *ngSwitchCase="trackStatuses.Downloading"
        class="inline-block px-3 py-1 text-xs font-bold rounded-full bg-purple-500/20 text-purple-400 border border-purple-500/30 animate-pulse"
        >DOWNLOADING</span
      >
      <span
        *ngSwitchCase="trackStatuses.Completed"
        class="inline-block px-3 py-1 text-xs font-bold rounded-full bg-spotify-green/20 text-spotify-green border border-spotify-green/30"
        >COMPLETED</span
      >
      <span
        *ngSwitchCase="trackStatuses.Error"
        class="inline-block px-3 py-1 text-xs font-bold rounded-full bg-red-500/20 text-red-400 border border-red-500/30"
        [title]="track.error"
        >ERROR</span
      >
    </ng-container>
  </div>
</a>
